### PR TITLE
Fix k3s socket

### PR DESCRIPTION
**Pull request by dahuang-purestorage**
**What this PR does / why we need it**:
This is a fix for STOR-553 and PWX-21842. Our rancher charts are failing at containerd.socket when installing on k3s and rke2 machines. (https://github.com/rancher/partner-charts/pull/251#issuecomment-987003407). This PR adds in the missing requirement for k3s and rke2 requirement. 

To add the requirement for k3s and rke2, this PR added:
- containerd-k3s mount path.
- allow running PX on master

**Which issue(s) this PR fixes** (optional)
STOR-553 and PWX-21842

**Special notes for your reviewer**:
Tested on k3s cluster and k8s cluster. Both worked as expected. 
The testing was done by installing the charts on the clusters with helm.

### CODE REVIEW

**Comment by trierra** [comment]
what is the issue #? why do we need this PR? please add all those info to the PR description

**Comment by trierra** [comment]
testing notes would be also helpful

**Comment by zoxpx** [comment]
I think this looks OK -- thanks Daniel

re @trierra -- afaik, this is required to support K3s and RKE2 distro's
* the latest Rancher2 is based off of K3s, but has a slightly different Kubernetes-version string, also
* for K3s-based distro's, we need to
  1. add `-v /run/k3s/containerd/containerd.sock:/run/containerd/containerd.sock` mount,
  2. allow running PX on master, and
  3. have to turn on the CSI   (since the K3s does not have in-tree Portworx driver)

BTW, is there a way to force-install of the CSI when K3s/RKE2 was detected?  (less of a concern, if we install the CSI by default)

**Review by zoxpx — APPROVED** [review]
I think this looks OK -- thanks Daniel

[would still be good if we had a better Description, and also if you could explain how you tested it]

**Comment by dahuang-purestorage** [comment]
> 

we don't have CSI install by default. i think there's a way to force using csi if rke2 or k3s is detected. is it required in addition to adding the containerd.sock mount?

**Comment by dahuang-purestorage** [comment]
Merging this for now. If we need to add CSI support, we can use another PR to merge in.

**Comment by zoxpx** [comment]
> > 
> 
> we don't have CSI install by default. i think there's a way to force using csi if rke2 or k3s is detected. is it required in addition to adding the containerd.sock mount?

Oh, in that case -- can we force the CSI installs on K3s/RKE installs?

Note that "regular" Portworx integration won't work on K3s/RKE2  (they stripped out the "default" Portworx driver from the Kubernetes code on that K8s distro, so one won't be able to create/use Portworx StorageClass -- unless it's through the CSI).

**Pull request merged**
