### PR TITLE
PWX-21842 Remove lighthouse

### PR DESCRIPTION
**Pull request by dahuang-purestorage**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** (optional)
Closes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by trierra** [comment]
lgtm

**Review by trierra — APPROVED** [review]

**Comment by dahuang-purestorage** [comment]
updated the PR to remove lighthouse completely as it's not being used/supported anymore

**Comment by trierra** [comment]
check the `/templates/_helpers.tpl` function `{{- define "px.getLighthouseImages" -}}` and remove that too

**Comment by dahuang-purestorage** [comment]
> check the `/templates/_helpers.tpl` function `{{- define "px.getLighthouseImages" -}}` and remove that too

good catch. updated :)

**Review by trierra — APPROVED** [review]
lgtm

**Pull request merged**
